# Generated by Django 3.1 on 2020-10-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('apellidoPaterno', models.CharField(max_length=15)),
                ('apellidoMaterno', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=15)),
                ('sexo', models.CharField(choices=[('F', 'femenino'), ('M', 'masculino')], default='F', max_length=1)),
                ('fechaNacimiento', models.DateField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=9)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=91)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.persona')),
            ],
        ),
    ]
